version: '3'
services:
  app1:
    build: ./app1
    depends_on:
      - redis

  app2:
    build: ./app2
    depends_on:
      - redis

  app3:
    build: ./app3
    depends_on:
      - redis

  redis:
    image: redis

  nginx-lb:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - app1
      - app2
      - app3
