version: '3'
services:
  app1:
    build: ./app1
    ports:
      - "5011:5000"

  app2:
    build: ./app2
    ports:
      - "5012:5000"

  app3:
    build: ./app3
    ports:
      - "5013:5000"

  nginx-app:
    image: nginx:alpine
    ports:
      - "5014:5000"

  nginx-lb:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
    - app1
    - app2
    - app3
